version: "3.0"
services:
  jsonrpc:
    image: harshjv/testrpc

  explorer:
    build: explorer
    depends_on:
      - jsonrpc

  bidding:
    build: bidding
    depends_on:
      - jsonrpc

  nginx-proxy:
    build: nginx-proxy
    ports:
      - 80:80
    depends_on:
      - jsonrpc
      - explorer
      - bidding
